-- TABELAS GEOGRÁFICAS

-- Tabela de Estados (UF)
/* MySQL/MSSQL: */
-- CREATE TABLE ESTADO (
-- idestado INT IDENTITY(1,1) PRIMARY KEY,
-- nome VARCHAR(50) NOT NULL,
-- uf CHAR(2) NOT NULL UNIQUE
-- );

/* XAMPP/MariaDB: */
CREATE TABLE ESTADO (
    idestado INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    uf CHAR(2) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de Cidades
/* MySQL/MSSQL: */
-- CREATE TABLE CIDADE (
-- idcidade INT IDENTITY(1,1) PRIMARY KEY,
-- nome VARCHAR(50) NOT NULL,
-- idestado INT NOT NULL,
-- FOREIGN KEY (idestado) REFERENCES ESTADO(idestado)
-- );

/* XAMPP/MariaDB: */
CREATE TABLE CIDADE (
    idcidade INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    idestado INT NOT NULL,
    FOREIGN KEY (idestado) REFERENCES ESTADO(idestado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de Bairros
/* MySQL/MSSQL: */
-- CREATE TABLE BAIRRO (
-- idbairro INT IDENTITY(1,1) PRIMARY KEY,
-- nome VARCHAR(50) NOT NULL,
-- idcidade INT NOT NULL,
-- FOREIGN KEY (idcidade) REFERENCES CIDADE(idcidade)
-- );

/* XAMPP/MariaDB: */
CREATE TABLE BAIRRO (
    idbairro INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    idcidade INT NOT NULL,
    FOREIGN KEY (idcidade) REFERENCES CIDADE(idcidade)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de Endereços
/* MySQL/MSSQL: */
-- CREATE TABLE ENDERECO (
-- idendereco INT IDENTITY(1,1) PRIMARY KEY,
-- logradouro VARCHAR(50) NOT NULL,
-- numero VARCHAR(10) NOT NULL,
-- complemento VARCHAR(30),
-- cep CHAR(9) NOT NULL,
-- idbairro INT NOT NULL,
-- FOREIGN KEY (idbairro) REFERENCES BAIRRO(idbairro)
-- );

/* XAMPP/MariaDB: */
CREATE TABLE ENDERECO (
    idendereco INT AUTO_INCREMENT PRIMARY KEY,
    logradouro VARCHAR(50) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    complemento VARCHAR(30),
    cep CHAR(9) NOT NULL,
    idbairro INT NOT NULL,
    FOREIGN KEY (idbairro) REFERENCES BAIRRO(idbairro)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABELA DE PESSOAS

-- Tabela de Pessoas
/* MySQL/MSSQL: */
-- CREATE TABLE PESSOAS (
-- idpessoa INT IDENTITY(1,1) PRIMARY KEY,
-- cpf CHAR(14) UNIQUE NOT NULL,
-- nome VARCHAR(50) NOT NULL,
-- sobrenome VARCHAR(50) NOT NULL,
-- data_nascimento DATE NOT NULL,
-- genero CHAR(1) CHECK (genero IN ('M', 'F', 'O')),
-- idendereco INT,
-- telefone VARCHAR(15),
-- email VARCHAR(100),
-- FOREIGN KEY (idendereco) REFERENCES ENDERECO(idendereco)
-- );

/* XAMPP/MariaDB: */
CREATE TABLE PESSOAS (
    idpessoa INT AUTO_INCREMENT PRIMARY KEY,
    cpf CHAR(14) UNIQUE NOT NULL,
    nome VARCHAR(50) NOT NULL,
    sobrenome VARCHAR(50) NOT NULL,
    data_nascimento DATE NOT NULL,
    genero CHAR(1) CHECK (genero IN ('M', 'F', 'O')),
    idendereco INT,
    telefone VARCHAR(15),
    email VARCHAR(100),
    FOREIGN KEY (idendereco) REFERENCES ENDERECO(idendereco)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- TABELAS ACADÊMICAS

-- Tabela de Ano Letivo
/* MySQL/MSSQL: */
-- CREATE TABLE ANO_LETIVO (
-- idanoLetivo INT IDENTITY(1,1) PRIMARY KEY,
-- ano CHAR(4) NOT NULL UNIQUE,
-- data_inicio DATE NOT NULL,
-- data_fim DATE NOT NULL,
-- semestre INT CHECK (semestre IN (1, 2))
-- );

/* XAMPP/MariaDB: */
CREATE TABLE ANO_LETIVO (
    idanoLetivo INT AUTO_INCREMENT PRIMARY KEY,
    ano CHAR(4) NOT NULL UNIQUE,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    semestre INT CHECK (semestre IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de Turmas
/* MySQL/MSSQL: */
-- CREATE TABLE TURMA (
-- idturma INT IDENTITY(1,1) PRIMARY KEY,
-- nome VARCHAR(30) NOT NULL,
-- turno VARCHAR(10) CHECK (turno IN ('MANHÃ', 'TARDE', 'NOITE')),
-- sala VARCHAR(10),
-- capacidade INT,
-- ANO_LETIVO_idAnoLetivo INT NOT NULL,
-- FOREIGN KEY (ANO_LETIVO_idAnoLetivo) REFERENCES ANO_LETIVO (idanoLetivo)
-- );

/* XAMPP/MariaDB: */
CREATE TABLE TURMA (
    idturma INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    turno VARCHAR(10) CHECK (turno IN ('MANHÃ', 'TARDE', 'NOITE')),
    sala VARCHAR(10),
    capacidade INT,
    ANO_LETIVO_idAnoLetivo INT NOT NULL,
    FOREIGN KEY (ANO_LETIVO_idAnoLetivo) REFERENCES ANO_LETIVO (idanoLetivo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de Disciplinas
/* MySQL/MSSQL: */
-- CREATE TABLE DISCIPLINA (
-- iddisciplina INT IDENTITY(1,1) PRIMARY KEY,
-- nome VARCHAR(50) NOT NULL,
-- carga_horaria INT NOT NULL,
-- ementa TEXT
-- );

/* XAMPP/MariaDB: */
CREATE TABLE DISCIPLINA (
    iddisciplina INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    carga_horaria INT NOT NULL,
    ementa TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de Alunos
/* MySQL/MSSQL: */
-- CREATE TABLE ALUNO(
-- RM INT IDENTITY (1,1) PRIMARY KEY,
-- EMAIL_INSTITUCIONAL VARCHAR(100) NOT NULL UNIQUE,
-- IDPESSOA INT NOT NULL UNIQUE,
-- DATA_INGRESSO DATE NOT NULL,
-- STATUS VARCHAR(20) CHECK (STATUS IN ('ATIVO', 'INATIVO', 'TRANCADO', 'FORMADO')),
-- FOREIGN KEY (IDPESSOA) REFERENCES PESSOAS(idpessoa)
-- );

/* XAMPP/MariaDB: */
CREATE TABLE ALUNO(
    RM INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL_INSTITUCIONAL VARCHAR(100) NOT NULL UNIQUE,
    IDPESSOA INT NOT NULL UNIQUE,
    DATA_INGRESSO DATE NOT NULL,
    STATUS VARCHAR(20) CHECK (STATUS IN ('ATIVO', 'INATIVO', 'TRANCADO', 'FORMADO')),
    FOREIGN KEY (IDPESSOA) REFERENCES PESSOAS(idpessoa)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de Professores
/* MySQL/MSSQL: */
-- CREATE TABLE PROFESSOR(
-- IDPROFESSOR INT IDENTITY(1,1) PRIMARY KEY,
-- DATA_ADMISSAO DATE NOT NULL,
-- FORMACAO VARCHAR(50) NOT NULL,
-- TITULACAO VARCHAR(30),
-- IDPESSOA INT NOT NULL UNIQUE,
-- STATUS VARCHAR(20) CHECK (STATUS IN ('ATIVO', 'AFASTADO', 'LICENCIADO', 'APOSENTADO')),
-- FOREIGN KEY (idpessoa) REFERENCES PESSOAS(idpessoa)
-- );

/* XAMPP/MariaDB: */
CREATE TABLE PROFESSOR(
    IDPROFESSOR INT AUTO_INCREMENT PRIMARY KEY,
    DATA_ADMISSAO DATE NOT NULL,
    FORMACAO VARCHAR(50) NOT NULL,
    TITULACAO VARCHAR(30),
    IDPESSOA INT NOT NULL UNIQUE,
    STATUS VARCHAR(20) CHECK (STATUS IN ('ATIVO', 'AFASTADO', 'LICENCIADO', 'APOSENTADO')),
    FOREIGN KEY (idpessoa) REFERENCES PESSOAS(idpessoa)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de Matrículas
/* MySQL/MSSQL: */
-- CREATE TABLE MATRICULA(
-- IDMATRICULA INT IDENTITY(1,1) PRIMARY KEY,
-- RM INT NOT NULL,
-- IDTURMA INT NOT NULL,
-- NUMERO_CHAMADA INT NOT NULL,
-- DATA_MATRICULA DATE NOT NULL,
-- TIPO_MATRICULA VARCHAR(20) CHECK (TIPO_MATRICULA IN ('MATRÍCULA INICIAL', 'REMATRÍCULA', 'TRANSFERÊNCIA')),
-- STATUS VARCHAR(20) CHECK (STATUS IN ('ATIVO', 'INATIVO', 'TRANSFERIDO')),
-- FOREIGN KEY (RM) REFERENCES ALUNO(RM),
-- FOREIGN KEY (idturma) REFERENCES TURMA(idturma)
-- );

/* XAMPP/MariaDB: */
CREATE TABLE MATRICULA(
    IDMATRICULA INT AUTO_INCREMENT PRIMARY KEY,
    RM INT NOT NULL,
    IDTURMA INT NOT NULL,
    NUMERO_CHAMADA INT NOT NULL,
    DATA_MATRICULA DATE NOT NULL,
    TIPO_MATRICULA VARCHAR(20) CHECK (TIPO_MATRICULA IN ('MATRÍCULA INICIAL', 'REMATRÍCULA', 'TRANSFERÊNCIA')),
    STATUS VARCHAR(20) CHECK (STATUS IN ('ATIVO', 'INATIVO', 'TRANSFERIDO')),
    FOREIGN KEY (RM) REFERENCES ALUNO(RM),
    FOREIGN KEY (idturma) REFERENCES TURMA(idturma)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de Disciplinas por Turma
/* MySQL/MSSQL: */
-- CREATE TABLE TURMADISCIPLINA(
-- IDTURMADISC INT IDENTITY(1,1) PRIMARY KEY,
-- IDTURMA INT NOT NULL,
-- IDDISCIPLINA INT NOT NULL,
-- IDPROFESSOR INT NOT NULL,
-- DIAS_AULA VARCHAR(20) NOT NULL,
-- HORARIO TIME NOT NULL,
-- FOREIGN KEY (IDTURMA) REFERENCES TURMA(IDTURMA),
-- FOREIGN KEY (IDDISCIPLINA) REFERENCES DISCIPLINA(IDDISCIPLINA),
-- FOREIGN KEY (IDPROFESSOR) REFERENCES PROFESSOR (IDPROFESSOR),
-- UNIQUE (IDTURMA, IDDISCIPLINA, IDPROFESSOR)
-- );

/* XAMPP/MariaDB: */
CREATE TABLE TURMADISCIPLINA(
    IDTURMADISC INT AUTO_INCREMENT PRIMARY KEY,
    IDTURMA INT NOT NULL,
    IDDISCIPLINA INT NOT NULL,
    IDPROFESSOR INT NOT NULL,
    DIAS_AULA VARCHAR(20) NOT NULL,
    HORARIO TIME NOT NULL,
    FOREIGN KEY (IDTURMA) REFERENCES TURMA(IDTURMA),
    FOREIGN KEY (IDDISCIPLINA) REFERENCES DISCIPLINA(IDDISCIPLINA),
    FOREIGN KEY (IDPROFESSOR) REFERENCES PROFESSOR (IDPROFESSOR),
    UNIQUE (IDTURMA, IDDISCIPLINA, IDPROFESSOR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela de Notas
/* MySQL/MSSQL: */
-- CREATE TABLE NOTA(
-- idnota INT IDENTITY(1,1) PRIMARY KEY,
-- IDTURMADISC INT NOT NULL,
-- RM INT NOT NULL,
-- BIMESTRE INT CHECK (BIMESTRE BETWEEN 1 AND 4),
-- NOTA DECIMAL(4,2) CHECK (NOTA BETWEEN 0 AND 10),
-- FALTAS INT,
-- FOREIGN KEY (IDTURMADISC) REFERENCES TURMADISCIPLINA(IDTURMADISC),
-- FOREIGN KEY (RM) REFERENCES ALUNO(RM),
-- UNIQUE (IDTURMADISC, RM, BIMESTRE)
-- );

/* XAMPP/MariaDB: */
CREATE TABLE NOTA(
    idnota INT AUTO_INCREMENT PRIMARY KEY,
    IDTURMADISC INT NOT NULL,
    RM INT NOT NULL,
    BIMESTRE INT CHECK (BIMESTRE BETWEEN 1 AND 4),
    NOTA DECIMAL(4,2) CHECK (NOTA BETWEEN 0 AND 10),
    FALTAS INT,
    FOREIGN KEY (IDTURMADISC) REFERENCES TURMADISCIPLINA(IDTURMADISC),
    FOREIGN KEY (RM) REFERENCES ALUNO(RM),
    UNIQUE (IDTURMADISC, RM, BIMESTRE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




/* Configurações adicionais pro XAMPP */
SET FOREIGN_KEY_CHECKS = 1;
SET SQL_MODE = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';